# -*- coding: utf-8 -*-
"""AI_Podcast_Gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zD6Yuetb49fPmSJNrNAgBZlZ4AcMiEHj
"""

# ============================================================
# 🎙️ AI Podcast Generator
# ============================================================

!pip install --quiet --upgrade openai gradio pydub gTTS

import os, re, time, gradio as gr
from openai import OpenAI
from gtts import gTTS
from pydub import AudioSegment
from pydub.effects import normalize, speedup

# ---------- 🔑 Set your OpenAI API key ----------
os.environ["OPENAI_API_KEY"] = ""  # 👈 replace with your API key
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# ---------- 🧠 Generate GPT Script ----------
def generate_script(topic="AI in India", minutes=3, lang="English"):
    prompt = f"""
Write a 2-person podcast (Host and Guest) about "{topic}".
Length: about {minutes} minutes.
Language: {lang}.
Output format only:
Host: ...
Guest: ...
Make it casual and friendly.
"""
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role":"user","content":prompt}],
        max_tokens=1200,
        temperature=0.8,
    )
    return resp.choices[0].message.content.strip()

# ---------- 🔊 gTTS Speech Synthesis ----------
def safe_tts(text, lang, filename):
    text = re.sub(r'[^A-Za-z0-9\u0C80-\u0CFF\u0B80-\u0BFF\u0900-\u097F .,?!]', '', text).strip()
    if not text:
        return False
    try:
        gTTS(text=text, lang=lang).save(filename)
        return True
    except Exception as e:
        print(f"⚠️ gTTS failed: {e}")
        return False

# ---------- 🎚️ Audio Speed Adjust ----------
def change_speed(audio, factor):
    """factor < 1 = slower, > 1 = faster"""
    if factor == 1.0:
        return audio
    new_frame_rate = int(audio.frame_rate * factor)
    altered = audio._spawn(audio.raw_data, overrides={"frame_rate": new_frame_rate})
    return altered.set_frame_rate(audio.frame_rate)

# ---------- 🎙️ Build Podcast ----------
def build_podcast(topic, minutes, lang_choice):
    lang_map = {
        "English": "en",
        "Hindi": "hi",
        "Kannada": "kn",
        "Tamil": "ta",
        "Telugu": "te"
    }
    lang_code = lang_map.get(lang_choice, "en")

    print(f"\n🧠 Generating script in {lang_choice}...")
    script = generate_script(topic, minutes, lang_choice)
    lines = [l.strip() for l in script.split("\n") if l.strip()]
    print(f"📝 {len(lines)} lines generated.")

    final = AudioSegment.silent(duration=600)

    for i, line in enumerate(lines):
        speaker = "host" if line.lower().startswith("host") else "guest"
        text = re.sub(r"^(Host|Guest):", "", line).strip()
        filename = f"seg_{i}.mp3"

        if not safe_tts(text, lang_code, filename):
            continue

        seg = AudioSegment.from_file(filename, format="mp3").fade_in(100).fade_out(100)

        # 🎚️ Host normal speed | Guest slower
        if speaker == "guest":
            seg = change_speed(seg, 0.9)

        final += seg + AudioSegment.silent(duration=250)

    final = normalize(final)
    out_file = "AI_Podcast.mp3"
    final.export(out_file, format="mp3", bitrate="192k")
    print("✅ Podcast ready!")
    return script, out_file

# ---------- 🎛️ Gradio Frontend ----------
def run_podcast(topic, minutes, language):
    script, mp3 = build_podcast(topic, minutes, language)
    return script, mp3

with gr.Blocks(title="🎧 AI Podcast Generator") as app:
    gr.Markdown(
        """
        # 🎧 AI Podcast Generator – Single Voice, Natural Flow
        Generate an AI podcast in your language!
        - Host: Normal speed
        - Guest: Slightly slower (for natural dialogue)
        - Supports: English, Hindi, Kannada, Tamil, Telugu
        """
    )

    with gr.Row():
        with gr.Column(scale=1):
            topic = gr.Textbox(label="🎙️ Podcast Topic", placeholder="e.g., Future of Artificial Intelligence in India")
            length = gr.Slider(1, 10, value=3, step=1, label="Podcast Length (minutes)")
            language = gr.Dropdown(
                ["English", "Hindi", "Kannada", "Tamil", "Telugu"],
                value="English", label="Language"
            )
            btn = gr.Button("🚀 Generate Podcast", variant="primary")

        with gr.Column(scale=1):
            output_script = gr.Textbox(label="🧠 GPT-Generated Script", lines=10)
            output_audio = gr.Audio(label="🎧 Podcast Output (MP3)")

    btn.click(run_podcast, [topic, length, language], [output_script, output_audio])

    gr.Markdown(
        """
        ---
        💡 **Notes:**
        - Uses one gTTS voice per language (more stable).
        - Guest voice slowed down for natural tone.
        - Works 100 % in Google Colab.
        """
    )

app.launch()